Automotriz/Automotriz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('core/', include('core.urls')),
]

Automotriz/core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    # Tipo
    path('tipo/list/', views.ListTipo.as_view(), name="tipo_list"),
    path('tipo/create/', views.CreateTipo.as_view(), name="tipo_create"),
    path('tipo/detail/<int:pk>/', views.DetailTipo.as_view(), name="tipo_detail"),
    path('tipo/update/<int:pk>/', views.UpdateTipo.as_view(), name="tipo_update"),
    path('tipo/delete/<int:pk>/', views.DeleteTipo.as_view(), name="tipo_delete"),
    
    # Puestos
    path('puesto/list/', views.ListPuesto.as_view(), name="puesto_list"),
    path('puesto/create/', views.CreatePuesto.as_view(), name="puesto_create"),
    path('puesto/detail/<int:pk>/', views.DetailPuesto.as_view(), name="puesto_detail"),
    path('puesto/update/<int:pk>/', views.UpdatePuesto.as_view(), name="puesto_update"),
    path('puesto/delete/<int:pk>/', views.DeletePuesto.as_view(), name="puesto_delete"),


    # Distribuidor
    path('distribuidor/list/', views.ListDistribuidor.as_view(), name="distribuidor_list"),
    path('distribuidor/create/', views.CreateDistribuidor.as_view(), name="distribuidor_create"),
    path('distribuidor/detail/<int:pk>/', views.DetailDistribuidor.as_view(), name="distribuidor_detail"),
    path('distribuidor/update/<int:pk>/', views.UpdateDistribuidor.as_view(), name="distribuidor_update"),
    path('distribuidor/delete/<int:pk>/', views.DeleteDistribuidor.as_view(), name="distribuidor_delete"),

    # Proveedor
    path('proveedor/list/', views.ListProveedor.as_view(), name="proveedor_list"),
    path('proveedor/create/', views.CreateProveedor.as_view(), name="proveedor_create"),
    path('proveedor/detail/<int:pk>/', views.DetailProveedor.as_view(), name="proveedor_detail"),
    path('proveedor/update/<int:pk>/', views.UpdateProveedor.as_view(), name="proveedor_update"),
    path('proveedor/delete/<int:pk>/', views.DeleteProveedor.as_view(), name="proveedor_delete"),

    # Categoria
    path('categoria/list/', views.ListCategoria.as_view(), name="categoria_list"),
    path('categoria/create/', views.CreateCategoria.as_view(), name="categoria_create"),
    path('categoria/detail/<int:pk>/', views.DetailCategoria.as_view(), name="categoria_detail"),
    path('categoria/update/<int:pk>/', views.UpdateCategoria.as_view(), name="categoria_update"),
    path('categoria/delete/<int:pk>/', views.DeleteCategoria.as_view(), name="categoria_delete"),

    # EstadoPedido
    path('estadopedido/list/', views.ListEstadoPedido.as_view(), name="estadopedido_list"),
    path('estadopedido/create/', views.CreateEstadoPedido.as_view(), name="estadopedido_create"),
    path('estadopedido/detail/<int:pk>/', views.DetailEstadoPedido.as_view(), name="estadopedido_detail"),
    path('estadopedido/update/<int:pk>/', views.UpdateEstadoPedido.as_view(), name="estadopedido_update"),
    path('estadopedido/delete/<int:pk>/', views.DeleteEstadoPedido.as_view(), name="estadopedido_delete"),
    
    # EstadoTransporte
    path('estadotransporte/list/', views.ListEstadoTransporte.as_view(), name="estadotransporte_list"),
    path('estadotransporte/create/', views.CreateEstadoTransporte.as_view(), name="estadotransporte_create"),
    path('estadotransporte/detail/<int:pk>/', views.DetailEstadoTransporte.as_view(), name="estadotransporte_detail"),
    path('estadotransporte/update/<int:pk>/', views.UpdateEstadoTransporte.as_view(), name="estadotransporte_update"),
    path('estadotransporte/delete/<int:pk>/', views.DeleteEstadoTransporte.as_view(), name="estadotransporte_delete"),
  
    # Departamento
    path('departamento/list/', views.ListDepartamento.as_view(), name="departamento_list"),
    path('departamento/create/', views.CreateDepartamento.as_view(), name="departamento_create"),
    path('departamento/detail/<int:pk>/', views.DetailDepartamento.as_view(), name="departamento_detail"),
    path('departamento/update/<int:pk>/', views.UpdateDepartamento.as_view(), name="departamento_update"),
    path('departamento/delete/<int:pk>/', views.DeleteDepartamento.as_view(), name="departamento_delete"),
   
    # Empleado
    path('empleado/list/', views.ListEmpleado.as_view(), name="empleado_list"),
    path('empleado/create/', views.CreateEmpleado.as_view(), name="empleado_create"),
    path('empleado/detail/<int:pk>/', views.DetailEmpleado.as_view(), name="empleado_detail"),
    path('empleado/update/<int:pk>/', views.UpdateEmpleado.as_view(), name="empleado_update"),
    path('empleado/delete/<int:pk>/', views.DeleteEmpleado.as_view(), name="empleado_delete"),
   
     # Transporte
    path('transporte/list/', views.ListTransporte.as_view(), name="transporte_list"),
    path('transporte/create/', views.CreateTransporte.as_view(), name="transporte_create"),
    path('transporte/detail/<int:pk>/', views.DetailTransporte.as_view(), name="transporte_detail"),
    path('transporte/update/<int:pk>/', views.UpdateTransporte.as_view(), name="transporte_update"),
    path('transporte/delete/<int:pk>/', views.DeleteTransporte.as_view(), name="transporte_delete"),
   
    # Planta
    path('planta/list/', views.ListPlanta.as_view(), name="planta_list"),
    path('planta/create/', views.CreatePlanta.as_view(), name="planta_create"),
    path('planta/detail/<int:pk>/', views.DetailPlanta.as_view(), name="planta_detail"),
    path('planta/update/<int:pk>/', views.UpdatePlanta.as_view(), name="planta_update"),
    path('planta/delete/<int:pk>/', views.DeletePlanta.as_view(), name="planta_delete"),
   
    # Producto
    path('producto/list/', views.ListProducto.as_view(), name="producto_list"),
    path('producto/create/', views.CreateProducto.as_view(), name="producto_create"),
    path('producto/detail/<int:pk>/', views.DetailProducto.as_view(), name="producto_detail"),
    path('producto/update/<int:pk>/', views.UpdateProducto.as_view(), name="producto_update"),
    path('producto/delete/<int:pk>/', views.DeleteProducto.as_view(), name="producto_delete"),
    
    # Pedido
    path('pedido/list/', views.ListPedido.as_view(), name="pedido_list"),
    path('pedido/create/', views.CreatePedido.as_view(), name="pedido_create"),
    path('pedido/detail/<int:pk>/', views.DetailPedido.as_view(), name="pedido_detail"),
    path('pedido/update/<int:pk>/', views.UpdatePedido.as_view(), name="pedido_update"),
    path('pedido/delete/<int:pk>/', views.DeletePedido.as_view(), name="pedido_delete"),

    # Almacen
    path('almacen/list/', views.ListAlmacen.as_view(), name="almacen_list"),
    path('almacen/create/', views.CreateAlmacen.as_view(), name="almacen_create"),
    path('almacen/detail/<int:pk>/', views.DetailAlmacen.as_view(), name="almacen_detail"),
    path('almacen/update/<int:pk>/', views.UpdateAlmacen.as_view(), name="almacen_update"),
    path('almacen/delete/<int:pk>/', views.DeleteAlmacen.as_view(), name="almacen_delete"),

    # Factura
    path('factura/list/', views.ListFactura.as_view(), name="factura_list"),
    path('factura/create/', views.CreateFactura.as_view(), name="factura_create"),
    path('factura/detail/<int:pk>/', views.DetailFactura.as_view(), name="factura_detail"),
    path('factura/update/<int:pk>/', views.UpdateFactura.as_view(), name="factura_update"),
    path('factura/delete/<int:pk>/', views.DeleteFactura.as_view(), name="factura_delete"),

    # AlmacenProducto
    path('almacenproducto/list/', views.ListAlmacenProducto.as_view(), name="almacenproducto_list"),
    path('almacenproducto/create/', views.CreateAlmacenProducto.as_view(), name="almacenproducto_create"),
    path('almacenproducto/detail/<int:pk>/', views.DetailAlmacenProducto.as_view(), name="almacenproducto_detail"),
    path('almacenproducto/update/<int:pk>/', views.UpdateAlmacenProducto.as_view(), name="almacenproducto_update"),
    path('almacenproducto/delete/<int:pk>/', views.DeleteAlmacenProducto.as_view(), name="almacenproducto_delete"),

    # PedidoProducto
    path('pedidoproducto/list/', views.ListPedidoProducto.as_view(), name="pedidoproducto_list"),
    path('pedidoproducto/create/', views.CreatePedidoProducto.as_view(), name="pedidoproducto_create"),
    path('pedidoproducto/detail/<int:pk>/', views.DetailPedidoProducto.as_view(), name="pedidoproducto_detail"),
    path('pedidoproducto/update/<int:pk>/', views.UpdatePedidoProducto.as_view(), name="pedidoproducto_update"),
    path('pedidoproducto/delete/<int:pk>/', views.DeletePedidoProducto.as_view(), name="pedidoproducto_delete"),

    ]

Automotriz/core/models.py
from django.db import models

# Create your models here.
class Puesto(models.Model):
    numero = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    ubicacion = models.CharField(max_length=20)

class Tipo(models.Model):
    numero = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=60)

class Distribuidor(models.Model):
    numero = models.AutoField(primary_key=True)
    dir_calle = models.CharField(max_length=30)
    dir_numero = models.CharField(max_length=10)
    dir_colonia = models.CharField(max_length=30)
    dir_cp = models.CharField(max_length=5)
    nombre = models.CharField(max_length=30)
    cantacto_nombre = models.CharField(max_length=30)
    contacto_apellido_paterno = models.CharField(max_length=30)
    contacto_apellido_materno = models.CharField(max_length=30)
    caontacto_numero_telefono = models.CharField(max_length=15)

class Proveedor(models.Model):
    numero = models.AutoField(primary_key=True)
    dir_calle = models.CharField(max_length=30)
    dir_numero = models.CharField(max_length=10)
    dir_colonia = models.CharField(max_length=30)
    dir_cp = models.CharField(max_length=5)
    nombre = models.CharField(max_length=30)
    contacto_nombre = models.CharField(max_length=30)
    contacto_apellido_paterno = models.CharField(max_length=30)
    contacto_apellido_materno = models.CharField(max_length=30)
    contacto_numero_telefono = models.CharField(max_length=15)

    def __str__(self):
        return self.nombre
    

class Categoria(models.Model):
    numero = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=60)

class EstadoPedido(models.Model):
    numero = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=60)

class EstadoTransporte(models.Model):
    numero = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=60)

class Departamento(models.Model):
    numero = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=60)
    descripcion = models.CharField(max_length=60)
    puesto = models.ForeignKey('Puesto', on_delete=models.CASCADE)

class Empleado(models.Model):
    numero = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=60)
    descripcion = models.CharField(max_length=60)
    nombre = models.CharField(max_length=30)
    apellido_paterno = models.CharField(max_length=30)
    apellido_materno = models.CharField(max_length=30)
    puesto = models.ForeignKey('Puesto', on_delete=models.CASCADE)

class Transporte(models.Model):
    numero = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=60)
    empleado = models.ForeignKey('Empleado', on_delete=models.CASCADE)
    tipo = models.ForeignKey('Tipo', on_delete=models.CASCADE)
    estado = models.ForeignKey('EstadoTransporte', on_delete=models.CASCADE)  # Corregido el nombre del modelo


class Planta(models.Model):
    numero = models.AutoField(primary_key=True)
    dir_calle = models.CharField(max_length=30)
    dir_numero = models.CharField(max_length=10)
    dir_colonia = models.CharField(max_length=30)
    dir_cp = models.CharField(max_length=5)
    numero_telefono = models.CharField(max_length=15)
    proveedor = models.ForeignKey('Proveedor', on_delete=models.CASCADE)
    empleado = models.ForeignKey('Empleado', on_delete=models.CASCADE)

class Producto(models.Model):
    numero = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=60)
    precio = models.FloatField()
    proveedor = models.ForeignKey('Proveedor', on_delete=models.CASCADE)
    distribuidor = models.ForeignKey('Distribuidor', on_delete=models.CASCADE)
    categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)

class Pedido(models.Model):
    numero = models.AutoField(primary_key=True)
    fecha = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    cantidad = models.IntegerField()
    precio_total = models.FloatField()
    planta = models.ForeignKey('Planta', on_delete=models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    distribuidor = models.ForeignKey('Distribuidor', on_delete=models.CASCADE)
    transporte = models.ForeignKey('Transporte', on_delete=models.CASCADE)
    estado = models.ForeignKey('EstadoPedido', on_delete=models.CASCADE)

    

class Almacen(models.Model):
    numero = models.AutoField(primary_key=True)
    fecha = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    responsable = models.CharField(max_length=30)
    nombre = models.CharField(max_length=30)
    apellido_paterno = models.CharField(max_length=30)
    apellido_materno = models.CharField(max_length=30)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)


class Factura(models.Model):
    numero = models.AutoField(primary_key=True)
    fecha_facturacion = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=False)
    importe = models.FloatField()
    iva = models.FloatField()
    total = models.FloatField()
    pedido = models.ForeignKey('Pedido', on_delete=models.CASCADE)

class AlmacenProducto(models.Model):
    almacen = models.ForeignKey('Almacen', on_delete=models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    stock = models.IntegerField()

class PedidoProducto(models.Model):
    pedido = models.ForeignKey('Pedido', on_delete=models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    importe = models.FloatField()
    cantidad = models.IntegerField()

Automotriz/templates/core/distribuidor/distribuidor_create.html
{% extends "base/base.html" %}
{% block content %}
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <!-- Nav Item - Alerts -->
                        <li class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-bell fa-fw"></i>
                                <!-- Counter - Alerts -->
                                <span class="badge badge-danger badge-counter">3+</span>
                            </a>
                            <!-- Dropdown - Alerts -->
                            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="alertsDropdown">
                                <h6 class="dropdown-header">
                                    Alerts Center
                                </h6>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="mr-3">
                                        <div class="icon-circle bg-primary">
                                            <i class="fas fa-file-alt text-white"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <div class="small text-gray-500">December 12, 2019</div>
                                        <span class="font-weight-bold">A new monthly report is ready to download!</span>
                                    </div>
                                </a>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="mr-3">
                                        <div class="icon-circle bg-success">
                                            <i class="fas fa-donate text-white"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <div class="small text-gray-500">December 7, 2019</div>
                                        $290.29 has been deposited into your account!
                                    </div>
                                </a>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="mr-3">
                                        <div class="icon-circle bg-warning">
                                            <i class="fas fa-exclamation-triangle text-white"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <div class="small text-gray-500">December 2, 2019</div>
                                        Spending Alert: We've noticed unusually high spending for your account.
                                    </div>
                                </a>
                                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                            </div>
                        </li>

                        <!-- Nav Item - Messages -->
                        <li class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-envelope fa-fw"></i>
                                <!-- Counter - Messages -->
                                <span class="badge badge-danger badge-counter">7</span>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="messagesDropdown">
                                <h6 class="dropdown-header">
                                    Message Center
                                </h6>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="img/undraw_profile_1.svg"
                                            alt="...">
                                        <div class="status-indicator bg-success"></div>
                                    </div>
                                    <div class="font-weight-bold">
                                        <div class="text-truncate">Hi there! I am wondering if you can help me with a
                                            problem I've been having.</div>
                                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                                    </div>
                                </a>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="img/undraw_profile_2.svg"
                                            alt="...">
                                        <div class="status-indicator"></div>
                                    </div>
                                    <div>
                                        <div class="text-truncate">I have the photos that you ordered last month, how
                                            would you like them sent to you?</div>
                                        <div class="small text-gray-500">Jae Chun · 1d</div>
                                    </div>
                                </a>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="img/undraw_profile_3.svg"
                                            alt="...">
                                        <div class="status-indicator bg-warning"></div>
                                    </div>
                                    <div>
                                        <div class="text-truncate">Last month's report looks great, I am very happy with
                                            the progress so far, keep up the good work!</div>
                                        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                                    </div>
                                </a>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                                            alt="...">
                                        <div class="status-indicator bg-success"></div>
                                    </div>
                                    <div>
                                        <div class="text-truncate">Am I a good boy? The reason I ask is because someone
                                            told me that people say this to all dogs, even if they aren't good...</div>
                                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                                    </div>
                                </a>
                                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                    src="img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <form action="" method="post">
                        {% csrf_token %}
                            {{ form }}
                            <br><hr>
                            <button type="submit" class="btn btn-outline-success">CREAR</button>
                            <br>
                    </form>            

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
{% endblock content %}

Automotriz/templates/core/distribuidor/distribuidor_list.html
{% extends "base/base.html" %}

{% block content %}
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Distribuidor</h1>

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-body">
                            <div class="table-responsive">
                                <a href="{% url 'core:distribuidor_create' %}"> Crear Distribuidor</a>
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <th>NUMERO</th>
                                        <th>CALLE</th>
                                        <th>NUMERO INTERIOR</th>
                                        <th>COLONIA</th>
                                        <th>CODIGO POSTAL</th>
                                        <th>NOMBRE</th>
                                        <th>CONTACTO</th>
                                        <th>APELLIDO MATERNO</th>
                                        <th>APELLIDO PATERNO</th>
                                        <th>TELEFONO</th>
                                    </thead>
                                    <tbody>
                                        {% for gg in distribuidor %}
                                            <tr>
                                                <td>{{ gg.numero }}</td>
                                                <td>{{ gg.dir_calle }}</td>
                                                <td>{{ gg.dir_numero }}</td>
                                                <td>{{ gg.dir_colonia }}</td>
                                                <td>{{ gg.dir_cp }}</td>
                                                <td>{{ gg.nombre }}</td>
                                                <td>{{ gg.cantacto_nombre }}</td>
                                                <td>{{ gg.contacto_apellido_paterno }}</td>
                                                <td>{{ gg.contacto_apellido_materno }}</td>
                                                <td>{{ gg.caontacto_numero_telefono }}</td>
                                                <td><a href="{% url 'core:distribuidor_detail' gg.numero %}" class="btn btn-outline-info"> Detail </a></td>
                                                <td><a href="{% url 'core:distribuidor_update' gg.numero %}" class="btn btn-outline-warning"> Update</a></td>
                                                <td><a href="{% url 'core:distribuidor_delete' gg.numero %}" class="btn btn-outline-danger">Delete</a></td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                            
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
{% endblock content %}